liferay/liferay-ckeditor

- ck.sh
Running shellcheck[1] finds a number of "Bash-isms" and a few other issues:
- SC2006: Use $(...) notation instead of legacy backticked `...`.
(https://www.shellcheck.net/wiki/SC2006)
- SC2039: In POSIX sh, &> is undefined.
(https://www.shellcheck.net/wiki/SC2039)
- SC2086: Double quote to prevent globbing and word splitting.
(https://www.shellcheck.net/wiki/SC2086)
- SC2112: 'function' keyword is non-standard. Delete it.
(https://www.shellcheck.net/wiki/SC2112)
- SC2162: read without -r will mangle backslashes.
(https://www.shellcheck.net/wiki/SC2162)
Full output:
https://gist.github.com/wincent/6de88b13a10f9609e7f6293f27dab3da
Rather than fix all of those, I switched the shebang line to `#!/bin/bash`, and then fixed the smaller number of remaining issues:
- SC2006: Use $(...) notation …
> chore: apply shellcheck fixes to ck.sh

- ck.sh
This fixes broken `ck.sh patch` on some machines.
We have observed some different behavior testing this on a Windows machine running a different version of Git:
- On the Windows version being tested, `git submodule` would print the *worktree* SHA1 of the submodule.
- On macOS, it would print the *index* (or HEAD) SHA1.
- Additionally, I noticed that the behavior was different if run interactively or as part of a script: interactively, I was getting the worktree SHA1; in the script I was getting the index/HEAD SHA1.
This manifested on windows as always producing empty patch sets because it would effectively run commands like:
git log --oneline HEAD..HEAD
git format-patch HEAD -o ../patches
when it should have been running ones like:
git log --oneline $PREVIOUS_HEAD..HEAD
git format-patch …
> fix: work around different Git behavior across versions

- patches/0001-patch-LPS-89596-Changed-position-of-drag-icon-for-IE.patch
- patches/0002-LPS-95472-Use-width-inherit-instead-of-width-100-to-.patch
Please check my patch.
https://issues.liferay.com/browse/LPS-95472
> fix: tabs in popups overflowing in CKEditor with "maximize" plugin (LPS-95472)

- ck.sh
The `git log` command we were using here is sensitive to user-local configuration (see the "log.decorate" option in `man git-config`, for example), which means that one user running the update might produce a commit message like:
Update ckeditor-dev to e1836357e (HEAD, tag: 4.11.4, origin/release/4.11.x) SCAYT/WSC changelog corrected.
and another might produce:
Update ckeditor-dev to e1836357e (tag: 4.11.4) SCAYT/WSC changelog corrected.
Make it totally stable by explicitly providing a format string, which will make the messages look this this:
Update ckeditor-dev to 4.11.4
e1836357e (tag: 4.11.4) SCAYT/WSC changelog corrected.
The other small improvement here is avoiding the unnecessary fork of a separate "head" process by passing "-1" to `git log` with equivalent effect.
Test plan: Run …
> fix: stabilize formatting of autogenerated commits

- ck.sh
These lines are exact duplicates of an identical check that happens a few lines earlier in the script, so we don't need them.
> refactor: remove redundant check from "ck.sh patch"

- patches/0001-LPS-89596-Cannot-Drag-Image-from-top-content-line-in.patch
- patches/0002-LPS-95472-Tabs-in-popups-not-appears-correctly-in-ma.patch
Just a little thing that has been bugging me for a while now: our patch files were using inconsistent titles (one had a "patch:" prefix and the other didn't).
Seeing as these patches are always driven by changes needed in liferay-portal, and they always have LPS tickets associated with them, I dropped the prefix so that both start with an LPS number. I also tweaked the commit messages so that the title contains the issue title from JIRA (ie. the motivation for the change) and the body contains whatever additional explanation (ie. the details of the change) were previously in the commit message.
No impact on build structure (no code changes), so I am not going to redo the build.
> refactor: make patches consistent

- README.md
Just updates made while testing prior to release.
> docs: apply miscellaneous updates

- package.json
Because the 4.13.1-liferay.2 release that I just published contains only:
ckeditor
└── ckeditor.js
0 directories, 1 file
If you compare that with the previous one, you see:
ckeditor
...
├── ckeditor.js
....
└── styles.js
191 directories, 1287 files
Cause was almost certainly the addition of the `.gitignore` file in dc0f150772a112f87444a34f4, which `yarn` evidently takes as a cue to not ship anything at all other than the file indicated by the "main" field in the package.json.
Test plan: Run `npm publish --dry-run` and see that the tarball contents look a whole lot more healthy:
https://gist.github.com/wincent/97c394b6d14fe1418647c4c9088b021f
> fix: explicitly define files to be included in the release

- package.json
Analogous change to this one on the alloy-editor repo:
https://github.com/liferay/alloy-editor/pull/1374
Just in case anybody is ever foolhardy enough to try doing development on this repo on Windows.
> fix: make globs work on Windows

- README.md
Just noticed these while driving by the liferay-ckeditor repo.
> docs: fix grammar and typo issues in README

- .github/workflows/nodejs.yml
- build-config.js
Following the pattern as described here:
https://codyogden.blog/yarn-with-github-actions-ci-cd/
Which is to start with the "Node.js starter workflow" and edit from there.
Going with single Node version because `yarn ci` only checks formatting at this point.
Closes: https://github.com/liferay/liferay-ckeditor/issues/49
> feat: run "yarn ci" on PRs

- .github/workflows/nodejs.yml
Same as what I did in: https://github.com/liferay/liferay-frontend-guidelines/pull/138
Don't need to install Yarn because it is already there, and we can catch more errors by passing `--frozen-lockfile`.
> refactor: improve actions set-up

- .github/workflows/ci.yml
- README.md
Renames "Node.js CI" to "ci" and adds a badge showing status to the README.
> docs: add build status badge to README

- .github/semantic.yml
Using the same config as we've used successfully elsewhere (eg. [in AlloyEditor](https://github.com/liferay/alloy-editor/blob/840470674882e00d639e809a0ee3870b191cb23b/.github/semantic.yml)).
Noticed that we didn't have it configured already while reviewing [#59](https://github.com/liferay/liferay-ckeditor/pull/59).
> chore: set up semantic PR bot in this repo

- support/version.js
Broken by: 002fd0c56d5c304a0166b2fbced0d04058e26d73
> fix: bad path in support/version.js

- support/version.js
Because 5941e58ae0f25a39d7a507b5b38aa0d5af770c7a was only a partial fix.
> fix: other bad path in support/version.js

- README.md
- ck.sh
I'm tweaking `ck.sh` to make it safer, and updating the README, based on things I noticed while preparing [the release yesterday](https://github.com/liferay/liferay-ckeditor/releases/tag/v4.13.1-liferay.5).
Changes to `ck.sh`:
-   After building, explicitly do `git add ckeditor` instead of telling the user to "commit the result!". It is too easy for the user to do it wrong and accidentally commit unwanted submodule changes (ie. with any of `git add .`, `git add -A`, `git add -u`, or variants with `git add -f`, and possibly other variants).
-   Update logging to tell user the above, and that they should review the staged changes.
-   In one other place make it more explicit what you have to do to  "generate the patches": ie. tell the user they need to "cd .." and be clear that "generating …
> refactor: make build slightly safer

- package.json
- skins/moono-lexicon/colorpanel.css
- skins/moono-lexicon/dialog.css
- skins/moono-lexicon/dialog_ie.css
- skins/moono-lexicon/dialog_ie8.css
- skins/moono-lexicon/dialog_iequirks.css
- skins/moono-lexicon/editor.css
- skins/moono-lexicon/editor_gecko.css
- skins/moono-lexicon/editor_ie.css
- skins/moono-lexicon/editor_ie8.css
- skins/moono-lexicon/editor_iequirks.css
- skins/moono-lexicon/elementspath.css
- skins/moono-lexicon/mainui.css
- skins/moono-lexicon/menu.css
- skins/moono-lexicon/notification.css
- skins/moono-lexicon/panel.css
- skins/moono-lexicon/presets.css
- skins/moono-lexicon/reset.css
- skins/moono-lexicon/richcombo.css
- skins/moono-lexicon/toolbar.css
https://issues.liferay.com/browse/IFI-1773
Applying in the moono-lexicon skin the new Lexicon styles already implemented in portal so we can get rid of that styles there.
Once we merge this and release a new liferay-ckeditor version we will need to:
- Remove `_editor_ckeditor.scss`
- Remove `.html-editor.portlet` definition on the `editor_html.scss` theme file.
- Update `BaseCKEditorConfigContributor` to load `moono-lexicon` css instead of `frontend-css-web` one. 
Also I opened [an issue](https://github.com/liferay/liferay-ckeditor/issues/68) to discuss if we should support scss for skins. For this pr I harcoded colors instead using clay variables.
Steps to test this in portal:
- Run `ck.sh build` in `liferay-ckeditor`
- Remove `liferay-ckeditor` folder from `/modules/node_modules` in …
> feat: customize moono-lexicon skin

- skins/moono-lexicon/mainui.css
- skins/moono-lexicon/presets.css
Fixing styles for editable area on source editor mode.
Before:
After
> fix: styles for editable area on source editor mode | #71

- package.json
These are build-time only deps and do not belong in "devDependencies", and will drag a lot of garbage into liferay-portal.
Compare the size of a release prepared with these deps (eg. v4.13.1-liferay.7) with an earlier release (eg. v4.13.1-liferay.5):
mkdir current
cd !$
yarn init -y
yarn add liferay-ckeditor
du -sh
58M    .
find . -type f | wc -l
4376
yarn list | wc -l
200 # 1 of these is package itself, 2 are metadata
mkdir ../previous
cd !$
yarn init -y
yarn add liferay-ckeditor@v4.13.1-liferay.5
du -sh
11M    .
find . -type f | wc -l
1567
yarn list | wc -l
3 # 1 of these is package itself, 2 are metadata
ie. package grew from 11 MB (1,567 files, 0 dependencies) to 58M (4,376 files, 197 dependencies).
> fix: move dev deps out of "dependencies"

- README.md
ie. https://github.com/liferay/liferay-ckeditor/releases
We didn't do it for the https://github.com/liferay/liferay-ckeditor/releases/tag/v4.13.1-liferay.6 and https://github.com/liferay/liferay-ckeditor/releases/tag/v4.13.1-liferay.7 because it is not explicitly noted in the README, but it should be.
> docs: note need to update GitHub releases page

- README.md
There is no "buildskin" subcommand any more, because we folded that into the "build" subcommand.
> docs: update stale reference to non-existent "buildskin" subcommand

- README.md
Seeing as it happens automatically since 43074c10c7.
I previously tried to update the docs to describe the new behavior in 415322d2ea, but I missed this reference.
> docs: remove instruction to "git commit" after building

- CHANGELOG.md
Some of these were missing the necessary "v" prefix; that shouldn't happen in the future because of [this fix](https://github.com/liferay/liferay-npm-tools/pull/472).
In this commit, I'm just going back and fixing the broken links. Note that not all releases have the "v" prefix, because apparently we didn't prepare those releases in a consistent way:
- 4.13.1-liferay.4
- 4.13.1-liferay.1
- 4.11.4-liferay.1
- 4.11.3-liferay.0
We've had a ".yarnrc" with the "v" prefix set via "version-tag-prefix" since 1e1d26aeced (2020-02-13) though, so that should have at least prevented 4.13.1-liferay.4 from going out without a "v" prefix; I am guessing that that one was not published by the standard means (ie. by running `yarn version`), but we should make a point of always doing it that way (we've …
> docs: fix broken links in changelog

- skins/moono-lexicon/mainui.css
We changed the skin Alloy Editor is using for CKEditor in portal to `moono-lisa` since its styling was made based on that one, but we're still having problems when both Alloy Editor and CKEditor are in the page 'cause they share classnames such as `ckeditor_editable`:
Removing this css properties, that are not longer needed, fixes this particular problem.
> fix: remove positioning and size definition of the editable area as is notlonger needed and was interfering with alloy editor styling

- skins/moono-lexicon/mainui.css
This PR is the fix of the https://issues.liferay.com/browse/LPS-117074 bug when CKEditor breaks on resize. 
This bug occured because `moono-lexicon` skin’s `cke_chrome` class is missing border.
It is required because `resize` takes outer element’s border property to calculate width and height when resizing.
> fix: add border property to outer class required for resizing

- support/iconsClassesGenerator.js
Solving https://issues.liferay.com/browse/LPS-118249
Remove comments from svg icons on css classes generation.
Copyright comments were introduced to Clay svg on https://github.com/liferay/clay/commit/13ae645d0fd90da6be1100f11430af259ff2f2c7#diff-214a1e2a1d78797d9528f65bfa7504ee
> fix: remove comments from svg icons

- patches/0001-LPS-89596-Cannot-Drag-Image-from-top-content-line-in.patch
- patches/0002-LPS-95472-Tabs-in-popups-not-appears-correctly-in-ma.patch
- patches/0003-LPS-85326-Remove-check-for-Webkit-browsers.patch
- patches/0004-LPP-36989-Remove-obsolete-summary-field-from-table-e.patch
- patches/0005-LPS-112982-Add-additional-resource-URL-parameters.patch
- patches/0006-LPS-118624-Don-t-pass-languageId-to-css-files-reques.patch
Fixing https://issues.liferay.com/browse/LPS-118624
Patching ckeditor so `languageId` is not passed to `css` requests
> fix: Don't pass languageId to css files requests

- ck.sh
As described here:
https://github.com/liferay/liferay-ckeditor/pull/108#issuecomment-669938087
Some of the noise is due to the user doing the update using a different version of Git, so the version number changes.
Some of it is due to the total number of patches changes, so each subject must change too.
We can avoid both of these by adding the `--no-signature` and `--no-numbered` switches to our `git format-patch` call.
Note though that we can't really stop the SHA-1's from changing if a rebase or other mutation is involved, but they will probable stay stable otherwise.
Test plan:
1. Recreate patches and get [this cleaner output](https://github.com/liferay/liferay-ckeditor/commit/0b67c64af91dd710177fcf8372e02a62f9d9f7d5).
2. Recreate patches _again_ and see no changes.
cc @jbalsas …
> feat: reduce noise created by patch updates

- support/build-config.js
in order to complete [https://issues.liferay.com/browse/LPS-115747](https://issues.liferay.com/browse/LPS-115747),
enable the `image2` plugin which allows center align images as well as
resizing them
> refactor: enable the `image2` plugin

- skins/moono-lexicon/dialog.css
https://issues.liferay.com/browse/LPS-118292
Changes needed in `liferay-portal`:
- Remove `.cke_dialog .cke_dialog_ui_input_text` from `_editor_ckeditor.scss`
Styles for closing icon svg manually applied, not sure if it's worth to add support to automatically handle it in the `iconsCSSClassGenerator`
> feat: add styles for dialogs in moono-lexicon

- plugins/codemirror/dialogs/codemirrordialog.js
- plugins/codemirror/plugin.js
- plugins/codemirror/skins/default.css
This is the second part of the [LPS-118290](https://issues.liferay.com/browse/LPS-118290) task:
The `codemirror` plugin has been updated and now includes a dialog that
can be used to edit and preview the code, when the editor is in `source`
mode
Here's a screenshot of the dialog in action:
Notes: 
The preview for the source code is rendered in an `iframe` to be able to load the `contentsCss` (if any) passed in the editor's `config` - without affecting the dialog itself.
> feat: add codemirror dialog

- ck.sh
- plugins/imagespacingbox/plugin.js
- support/build-config.js
This PR is a follow up on https://github.com/liferay-frontend/liferay-portal/pull/313
The purpose of these changes is adding the possibility for user to add horizontal and vertical space to the image element in editor.
I achieved this by creating `imagespacingbox` plugin which adds 2 additional input fields in `image2` plugin dialog box.
Setting `hspace` value adds horizontal margin, `margin-left` and `margin-right` to image element selected in editor.
Setting `vspace` value adds vertical margin, `margin-left` and `margin-right` to image element selected in editor.
This solves the issue when editing the text next to image, where there was previously no space and allows the user possibility to add custom space replicating functionality we had with `image` plugin.
Additional modifications …
> feat: add imagespacingbox plugin

- plugins/codemirror/dialogs/codemirrordialog.js
This PR fixes an issue described in https://issues.liferay.com/browse/LPS-120758 ,visual bug in `Chrome` (scrollbar) and in `Firefox` (whitespace) in Source dialog box.
This issue was caused by `CodeMirror` plugin line number width not included in dialog size calculation.
To test this fix:
1. Build CKEditor with this change
2. Access to portal.
3. Go to Web Content.
4. Add a content.
5. In content field, click Source button in ckeditor toolbar to go to source view.
6. Type any text
7. Click the Expand icon next to the Source button to preview source dialog.
Before Chrome
Before Firefox
After Chrome
After Firefox
> fix: modify calculation for dialog defaultWidth which caused visual bug

- plugins/codemirror/dialogs/codemirrordialog.js
This PR is a fix for [LPS-120763](https://issues.liferay.com/browse/LPS-120763) - `"CKEditor - Formatted text doesn't display in Preview Source dialog on Firefox"` bug in `codemirror` plugin.
As described in the ticket, the issue happened when editing text and opening Source dialog in Firefox.
The added text would't appear in the code preview area.
This cause of this issue is that in Firefox, the frame's content is not recognised if there is no initial content set. 
To solve this we need to trigger a `page load` and then set `innerHtml` to `iFrame` preview.
--------------
To test this:
1. Build CKEditor with this change
2. Access to portal on Firefox browser.
3. Go to Web Content.
4. Add a content.
5. In content field, click Source button in ckeditor toolbar to go to source view.
6. Type …
> fix: display formatted text in Firefox Preview Source dialog

- plugins/codemirror/dialogs/codemirrordialog.js
- plugins/codemirror/plugin.js
- plugins/codemirror/skins/default.css
This solves the issue described in [LPS-120594](https://issues.liferay.com/browse/LPS-120549), where
occasionally the editor's source mode (now handled by the `codemirror`
plugin) grows depending on the text that is in the editor.
Here's a screenshot of what it looked like before this change:
And here's a screenshot of what it looks like after this change:
**Test plan**:
- Fetch this branch, and build `liferay-ckeditor` with `./ck.sh build`
- Use the previously built `liferay-ckeditor` in DXP. ([Instructions](https://github.com/liferay/liferay-ckeditor#testing-in-liferay-portal))
- In DXP, from the global menu, navigate to "Instance Settings > Email" and once the page is loaded, click on the "Source" button 
Another thought I had, is that if we were using ES6 in CKEDITOR plugins, 
we …
> fix: enable line wrapping in codemirror plugin

- plugins/codemirror/skins/default.css
In [`5de7cdb`](https://github.com/liferay/liferay-ckeditor/commit/5de7cdbed7e7e9b50cd5e77d5dc020e137b104a3) and [`1783acf`](https://github.com/liferay/liferay-ckeditor/commit/1783acf68ee470fa79619462e8c2df6f9ec39d4a)  we intended to fix text wrapping in the
`codemirror` (source view) plugin but this was apparently missing 
**Test plan**:
- Fetch this branch and build `liferay-ckeditor` with
```sh
./ck.sh build
```
- Use the previously built version of `liferay-ckeditor` in DXP
- Deploy the `frontend-editor-ckeditor-web` OSGi module
- Navigate to **Instance Settings** > **Email**
- Assert that the editors wrap text correctly
**Before**
**After**
> fix: make text wrap in codemirror plugin

- package.json
- support/copyPluginDependencies.js
- yarn.lock
This change is related to #139, instead of touching the minified files directly, here we use `@babel` to rename `define` to `__define_disabled__`: if someone can give me some pointers we could probably remove the entire `if`
but for the moment this fixes the issue.
> fix: rename define in plugin dependencies

- patches/0001-LPS-89596-Cannot-Drag-Image-from-top-content-line-in.patch
- patches/0002-LPS-95472-Tabs-in-popups-not-appears-correctly-in-ma.patch
- patches/0003-LPS-85326-Remove-check-for-Webkit-browsers.patch
- patches/0004-LPP-36989-Remove-obsolete-summary-field-from-table-e.patch
- patches/0005-LPS-112982-Add-additional-resource-URL-parameters.patch
- patches/0006-LPS-118624-Don-t-pass-languageId-to-css-files-reques.patch
- patches/0007-LPS-124728-Avoid-breaking-IE11.patch
We were using `URL`, `URLSearchParams` and `Object.entries`, 
which aren't supported in IE11 . In theory we have polyfills for these 
but apparently when `getUrl` is executed these polyfills aren't loaded yet.
So this patch reverts a previous patch and adds more .
Tested agaisn't [LPS-124728](https://issues.liferay.com/browse/LPS-124728) and [LPS-112982](https://issues.liferay.com/browse/LPS-112982)
> fix: LPS-124728 Avoid using unsupported APIs in IE11

- patches/0001-LPS-89596-Cannot-Drag-Image-from-top-content-line-in.patch
- patches/0002-LPS-95472-Tabs-in-popups-not-appears-correctly-in-ma.patch
- patches/0003-LPS-85326-Remove-check-for-Webkit-browsers.patch
- patches/0004-LPP-36989-Remove-obsolete-summary-field-from-table-e.patch
- patches/0005-LPS-112982-Add-additional-resource-URL-parameters.patch
- patches/0006-LPS-118624-Don-t-pass-languageId-to-css-files-reques.patch
- patches/0007-LPS-124728-Avoid-breaking-IE11.patch
- patches/0008-LPS-125559-Fix-width-for-the-following-fields-Cell-s.patch
On the table Properties modal window the following fields value are not visible
Border size
Cell padding
Cell spacing
The .cke_dialog_ui_labeled_content style should be width: 5em; instead of the width: 3em;
Fixes #149
**Before**
**After**
> fix: Make table properties visible

- skins/moono-lexicon/richcombo.css
Hey,
[LPS-125441](https://issues.liferay.com/browse/LPS-125441)
Our ckeditor skin had a flickering, as the focus and active state of the elements did not contain the necessary padding and margin values. This issue is not reproducible on master due to our toolbar change, however on 7.2.x where the toolbar still holds the same plugins, it is reproducible.
Please review my changes
> fix: LPS-125441 CKEditor font size selector flickers on mouse over

- package.json
- plugins/codemirror/deps.json
- plugins/codemirror/dialogs/codemirrordialog.js
- plugins/codemirror/plugin.js
- support/build-config.js
- yarn.lock
Hey,
[LPS-126202](https://issues.liferay.com/browse/LPS-126202)
By restoring [htmlwriter](https://ckeditor.com/cke4/addon/htmlwriter), the beautification issue is resolved in AlloyEditor.
This issue is not reproducible with ckeditor at the moment as we used _js-beautify_ to beautify the html when switching to source mode in our new source editor plugin -> [LPS-118290](https://issues.liferay.com/browse/LPS-118290)
Restoring the htmlwriter plugin resolves the issue in AlloyEditor and it's a battle tested solution we used for years.
Please review my changes, thanks
> fix: Restore htmlwriter to have beautification in our source view

- plugins/codemirror/plugin.js
Add an editable to the codemirror plugin, so that it also dispatches
the "change" event in source mode
This was copied directly from the original `sourcearea` plugin,
from [here](https://github.com/ckeditor/ckeditor4/blob/eb2d11644a796cd13cd047cd55541430359f9317/plugins/sourcearea/plugin.js#L48) and [here](https://github.com/ckeditor/ckeditor4/blob/eb2d11644a796cd13cd047cd55541430359f9317/plugins/sourcearea/plugin.js#L103-L133)
**Preview**
Fixes #153
> fix: update codemirror plugin

- patches/0001-LPS-89596-Cannot-Drag-Image-from-top-content-line-in.patch
- patches/0002-LPS-95472-Tabs-in-popups-not-appears-correctly-in-ma.patch
- patches/0003-LPS-85326-Remove-check-for-Webkit-browsers.patch
- patches/0004-LPP-36989-Remove-obsolete-summary-field-from-table-e.patch
- patches/0005-LPS-112982-Add-additional-resource-URL-parameters.patch
- patches/0006-LPS-118624-Don-t-pass-languageId-to-css-files-reques.patch
- patches/0007-LPS-124728-Avoid-breaking-IE11.patch
- patches/0008-LPS-125559-Fix-width-for-the-following-fields-Cell-s.patch
- patches/0009-LPS-127732-remove-css-classes-as-well-when-changing-.patch
Hey,
[LPS-127732](https://issues.liferay.com/browse/LPS-127732) (we can use this to update the ckeditor version in Liferay),
I modified the solution and generated a patch as suggested in https://github.com/liferay/liferay-ckeditor/pull/155
Please review it,
Thanks
> fix: remove css classes as well when changing style

- plugins/codemirror/dialogs/codemirrordialog.js
- plugins/codemirror/plugin.js
By using the `editable` function, we make sure the editor's content
is not lost when switching from wysiwyg to source mode, and
when opening the "preview" dialog.
**Before**
**After**
> fix: use CKEditor's `editable` to sync content between editor and dialogs

- plugins/codemirror/plugin.js
This is a follow up for #160, to fix [LPS-128735](https://issues.liferay.com/browse/LPS-128735), with the change I suggested [here](https://github.com/liferay/liferay-ckeditor/pull/160#discussion_r609864815)
> fix: initialize codemirror with the editor data and update it on data ready

- plugins/balloontoolbar/skins/moono-lexicon/balloontoolbar.css
This PR add the missing styles for the balloontoolbar
**Before**
**After**
> fix: LPS-127014 Add balloontoolbar missing style

- patches/0001-LPS-89596-Cannot-Drag-Image-from-top-content-line-in.patch
- patches/0002-LPS-95472-Tabs-in-popups-not-appears-correctly-in-ma.patch
- patches/0003-LPS-85326-Remove-check-for-Webkit-browsers.patch
- patches/0004-LPP-36989-Remove-obsolete-summary-field-from-table-e.patch
- patches/0005-LPS-112982-Add-additional-resource-URL-parameters.patch
- patches/0006-LPS-118624-Don-t-pass-languageId-to-css-files-reques.patch
- patches/0007-LPS-124728-Avoid-breaking-IE11.patch
- patches/0008-LPS-125559-Fix-width-for-the-following-fields-Cell-s.patch
- patches/0009-LPS-131699-Add-null-check.patch
Hello,
[LPS-131699](https://issues.liferay.com/browse/LPS-131699),
These changes will solve the issue on 7.3.x.
On master, the issue is not reproducible, because, on that branch, Web Content uses ckeditor4-react instead of liferay-ckeditor.
Please review the changes, thanks
> fix: add null check

- package.json
- skins/moono-lexicon/icons.json
- yarn.lock
In order to make sure have the latest icons avaible in `@clayui/css`
because we're going to need them for [LPS-132048](https://issues.liferay.com/browse/LPS-132048)
Additionally as part of [LPS-127012](https://issues.liferay.com/browse/LPS-127012),
we're adding more icons to our `moono-lexicon` skin that will be used in
the Balloon Editor
> fix: update @clayui/css to latest and add more icons

- plugins/balloontoolbar/skins/moono-lexicon/balloontoolbar.css
This fixes the visual glitch produced when selecting an element
in the CKEDITOR.ui.richCombo element used by the [Styles
Combo](https://ckeditor.com/cke4/addon/stylescombo) plugin
**Before**
**After**
**Warning**
Depends on #175 
[EDIT] If you think it's a better idea to fold these changes into #175, I can do it too.
> fix: remove unneeded styles

- patches/0001-LPS-89596-Cannot-Drag-Image-from-top-content-line-in.patch
- patches/0002-LPS-95472-Tabs-in-popups-not-appears-correctly-in-ma.patch
- patches/0003-LPS-85326-Remove-check-for-Webkit-browsers.patch
- patches/0004-LPP-36989-Remove-obsolete-summary-field-from-table-e.patch
- patches/0005-LPS-112982-Add-additional-resource-URL-parameters.patch
- patches/0006-LPS-118624-Don-t-pass-languageId-to-css-files-reques.patch
- patches/0007-LPS-124728-Avoid-breaking-IE11.patch
- patches/0008-LPS-125559-Fix-width-for-the-following-fields-Cell-s.patch
- patches/0009-LPS-131699-Add-null-check.patch
Hey @liferay,
Attached is an update for to upgrade CKEditor to [4.16.1](https://github.com/ckeditor/ckeditor4/tree/4.16.1).
Please let me know if you have any questions. Thanks!
> chore: update ckeditor-dev to 4.16.1

- plugins/codemirror/plugin.js
When we switched to  the `codemirror` plugin, right clicking in source mode no longer worked. 
By adding the `cke_enable_context_menu` CSS class to the `codemirror` plugin, 
the browser's native context menu is enabled.
See [LPS-134687](https://issues.liferay.com/browse/LPS-134687)
Fixes #180
Let me know if there are any questions or comments about this.
Thank you.
> fix: enable browser native menu in codemirror plugin

- plugins/imagespacingbox/plugin.js
Please see [LPS-134777](https://issues.liferay.com/browse/LPS-134777) for more information.
We could have multiple cases scenarios, take in mind that a user can change the source code as he likes, so we need to check on each dialogue display the styles of the selected image.
These are all the possible cases I found, if the user did:
1. not apply any style or hspace or vspace in the dialog, this will mean empty values
2. apply only hspace, the style would be: style="margin-left: 10px; margin-right: 10px;"
3. apply only one vspace, the style would be: style="margin-bottom: 10px; margin-top: 10px;"
4. apply hspace and vspace, the style would be: style="margin: 20px 10px;"
5. applied the same value for hspace and vspace, the style would be: style="margin: 10px;"
6. change this style from …
> fix: retrieve hspace and vspace values from style

- patches/0001-LPS-89596-Cannot-Drag-Image-from-top-content-line-in.patch
- patches/0002-LPS-95472-Tabs-in-popups-not-appears-correctly-in-ma.patch
- patches/0003-LPS-85326-Remove-check-for-Webkit-browsers.patch
- patches/0004-LPP-36989-Remove-obsolete-summary-field-from-table-e.patch
- patches/0005-LPS-112982-Add-additional-resource-URL-parameters.patch
- patches/0006-LPS-118624-Don-t-pass-languageId-to-css-files-reques.patch
- patches/0007-LPS-124728-Avoid-breaking-IE11.patch
- patches/0008-LPS-125559-Fix-width-for-the-following-fields-Cell-s.patch
- patches/0009-LPS-131699-Add-null-check.patch
- patches/0010-LPS-136119-Set-id-on-first-render-instead-of-changin.patch
Fixes: https://issues.liferay.com/browse/LPS-136119
To reproduce:
1. Place `frontend-editor-ckeditor-sample-web` on a page.
2. See movies of the bug the linked ticket.
3. Comment out [this block of code](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-editor/frontend-editor-ckeditor-web/src/main/resources/META-INF/resources/_diffs/plugins/ballooneditor/plugin.js#L387-L397), overriding of `CKEDITOR.ui.panel.prototype.showBlock`. This block is inadequate to fix this issue, and prevents the solution in this PR to work correctly.
The root cause of the issue is that `id` of buttons is changing [with each render](https://github.com/ckeditor/ckeditor4/blob/major/plugins/button/plugin.js#L146). On the other side, blocks are tied to `id` of the button that created them. …
> fix: LPS-136119 We can't open panel elements when the table toolbar is re-rendered

- patches/0001-LPS-89596-Cannot-Drag-Image-from-top-content-line-in.patch
- patches/0002-LPS-95472-Tabs-in-popups-not-appears-correctly-in-ma.patch
- patches/0003-LPS-85326-Remove-check-for-Webkit-browsers.patch
- patches/0004-LPP-36989-Remove-obsolete-summary-field-from-table-e.patch
- patches/0005-LPS-112982-Add-additional-resource-URL-parameters.patch
- patches/0006-LPS-118624-Don-t-pass-languageId-to-css-files-reques.patch
- patches/0007-LPS-124728-Avoid-breaking-IE11.patch
- patches/0008-LPS-125559-Fix-width-for-the-following-fields-Cell-s.patch
- patches/0009-LPS-131699-Add-null-check.patch
- patches/0010-LPS-136119-Set-id-on-first-render-instead-of-changin.patch
- patches/0011-LPS-136998-Avoid-breaking-the-UI-in-firefox.patch
This issue is we are putting contentEditable attribute to the body html, however it breaks the UI on Firefox. This change was introduce in https://dev.ckeditor.com/ticket/5560, reverting it does not reintroduce the issue.
Please review my changes,
Thanks! 
Fixes #186
> fix: Maximize plugin breaks the UI in Firefox

- patches/0001-LPS-89596-Cannot-Drag-Image-from-top-content-line-in.patch
- patches/0002-LPS-95472-Tabs-in-popups-not-appears-correctly-in-ma.patch
- patches/0003-LPS-85326-Remove-check-for-Webkit-browsers.patch
- patches/0004-LPP-36989-Remove-obsolete-summary-field-from-table-e.patch
- patches/0005-LPS-112982-Add-additional-resource-URL-parameters.patch
- patches/0006-LPS-118624-Don-t-pass-languageId-to-css-files-reques.patch
- patches/0007-LPS-124728-Avoid-breaking-IE11.patch
- patches/0008-LPS-125559-Fix-width-for-the-following-fields-Cell-s.patch
- patches/0009-LPS-131699-Add-null-check.patch
- patches/0010-LPS-136119-Set-id-on-first-render-instead-of-changin.patch
- patches/0011-LPS-136998-Avoid-breaking-the-UI-in-firefox.patch
- patches/0012-LPS-137425-Don-t-check-selection-on-focus.patch
Fixes: https://issues.liferay.com/browse/LPS-137425
In this PR, we are removing force selection update on `focus`. Selection update has a lot of side-effects, including opening a balloon toolbar. I tried multiple times to makes a workaround, see https://github.com/liferay-frontend/liferay-portal/pull/1284 and https://github.com/liferay-frontend/liferay-portal/pull/1350, but each solution leads to a new bug. I finally ran out of options, the only solution remaining to fix the root cause. 
I was hesitant to do modify base ckeditor because the comment references `previousActive` sync. Looking in more depth in the ckeditor code, I think removing this block is safe to do:
- I believe [this block](https://github.com/ckeditor/ckeditor4/blob/cae20318d46745cc46c811da4e7d68b38ca32449/core/selection. …
> fix: LPS-137425 Focusing on balloon editor toolbar may open an additional text toolbar

- patches/0013-LPS-139565-When-upgrading-from-6.2-to-7.1-image-widt.patch
https://issues.liferay.com/browse/LPS-139565
In earlier versions of CKEditor, it set the height and width of a resized image as style properties. However, in later versions of CKEditor, it instead sets element attributes instead. As a result, any content created with the earlier version of CKEditor will run into issues in the newer versions of CKEditor.
1. Navigate to the screen to create a new web content
2. Access the WYSIWYG editor and upload an image to the document library and add it to the content
3. Switch to the source view and add the `style="height:100px; width:100px"` attribute to the `img` tag to simulate content created in earlier versions of Liferay
4. Publish the web content
5. Edit the web content that you created
6. Attempt to resize the image using either the dragresizer …
> fix: [TS] LPS-139565

- skins/moono-lexicon/mainui.css
Open anywhere on DXP where the resize plugin was enabled. You could go to Web Content -> create new basic web content and take a look at the editor contained on the sidebar.
If you aren't viewing your DXP in Arabic, you'll see the drag handler of the resize is on the right side of the editor area. This is correct.
When enabling RTL, I mean enabling a language written from right to left, like Arab or Hebrew; you may see the drag handle still on the right side.
I noticed the styles on `moono-lexicon` that deals with RTL/LTR on `ckeditor` side are correct. If you take a look at [this page](https://ckeditor.com/ckeditor-4/demo/), you'll notice the class that is responsible for positioning the handler on the right side have the same name and the implementation as `moono-lexicon` but there is …
> fix: makes cke_resizer_rtl float to the right due to liferay-r2

- skins/moono-lexicon/richcombo.css
[LPS-163662](https://issues.liferay.com/browse/LPS-163662) Added margin to stop CKEditor element flickering.
This change was added based on the conversation on [PTR-3391](https://issues.liferay.com/browse/PTR-3391).
> fix: LPS-163662 CKEditor element flickering

- plugins/codemirror/dialogs/codemirrordialog.js
https://liferay.atlassian.net/browse/LPD-33910
https://liferay.atlassian.net/browse/LPP-55225
CodeMirror editor was not being sanitized and so adding sensitization prevents any unexpected behavior.
I tried several examples and was not able to get any unexpected behavior.
Please let me know if there are any questions or comments about this.
Thank you!
> LPD-33910 Add sanitization for codeMirror editor

- patches/0001-LPS-89596-Cannot-Drag-Image-from-top-content-line-in.patch
- patches/0002-LPS-95472-Tabs-in-popups-not-appears-correctly-in-ma.patch
- patches/0003-LPS-85326-Remove-check-for-Webkit-browsers.patch
- patches/0004-LPP-36989-Remove-obsolete-summary-field-from-table-e.patch
- patches/0005-LPS-112982-Add-additional-resource-URL-parameters.patch
- patches/0006-LPS-118624-Don-t-pass-languageId-to-css-files-reques.patch
- patches/0007-LPS-124728-Avoid-breaking-IE11.patch
- patches/0008-LPS-125559-Fix-width-for-the-following-fields-Cell-s.patch
- patches/0009-LPS-131699-Add-null-check.patch
- patches/0010-LPS-136119-Set-id-on-first-render-instead-of-changin.patch
- patches/0011-LPS-136998-Avoid-breaking-the-UI-in-firefox.patch
- patches/0012-LPS-137425-Don-t-check-selection-on-focus.patch
- patches/0013-LPS-139565-When-upgrading-from-6.2-to-7.1-image-widt.patch
- patches/0014-LPS-137763-If-contentsElement-is-defined-use-it-as-a.patch
- patches/0015-LPS-166086-Make-dialog-close-button-accessible-with-.patch
- patches/0016-LPD-19992-Validate-id-and-name-fields-according-to-s.patch
- patches/0017-LPD-20726-Always-set-some-width-to-img-container.patch
- patches/0018-LPD-33712-Add-css-to-combopanel-when-maximized.patch
- patches/0019-LPD-35604-Add-title-to-iframe.patch
- patches/0020-LPD-42473-Set-a-width-based-on-px-so-it-does-not-aff.patch
- patches/0021-LPD-42473-Instead-of-setting-a-width-from-image2-plu.patch
Hi,
This new patch (#21) is basically reverting our previous tries (#20, #17) to render images with no width. 
After a deeper analysis, we've seen none of these solutions is working 100% and this issue should be better handled inside Liferay Portal, to be more exact, within [itemselector](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-editor/frontend-editor-ckeditor-web/src/main/resources/META-INF/resources/_diffs/plugins/itemselector/plugin.js#L248-L288) plugin.
Once this pr gets merged, I'll release a new liferay-ckeditor version, and then I'll send a pull request to liferay-portal upgrade such version and including the fix within itemselector plugin.
Thanks.
Regards.
> LPD-42473 Instead of setting a width from image2 plugin, we'll do it in portal
